---
apiVersion: v1
kind: Secret
metadata:
  name: kdubois2-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-lab/kdubois2-gateway-gitops
